= Victoreen Robert Elliot - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: EazyTutors

---

== Overview

EazyTutors

== Summary of contributions

* *Major enhancement*: Grade Statistics
** What it does: Calculates the statistics for the grades of an individual assignment or the overall class.
** Justification: This feature enables tutors to analyse the grades of students to provide relative feedback based on the performance of the class.
** Highlights: Provides high, low, 25th/75th percentiles, average, and median of the grades.
** Credits:

* *Major enhancement*: Attendance Model
** What it does: Provides a representation of an attendance session for a particular date.
** Justification: This enhancement provides the model for the attendance feature.
** Highlights: This enables a mapping between each student and multiple attendance sessions
               with a record of attendance/absense for that session.
** Credits:

* *Minor enhancement*: Calculate and display the assignment grades when a student is selected.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-W12-4/main/commits/master?author=robertvictoreen] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Review pull requests:
** Enhancements to existing features:
***
** Documentation:
*** UserGuide / DeveloperGuide
** Community:
***
** Tools:
***

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=assignmentstats]

include::../UserGuide.adoc[tag=classstats]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=attendance]


== PROJECT:

---

_{Optionally, you may include other projects in your portfolio.}_
