= Victoreen Robert Elliot - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: EazyTutors

---

== Overview

=== Purpose
* This project portfolio was written to document my role and contributions to the **EazyTutors** project. I was responsible for the class and assignment statistics feature and display.

=== The Team
* My team comprises of students from the National University of Singapore and we decided on creating this application after observing the hassle tutors have to deal with when marking attendance.

=== The Application
* EazyTutors is a desktop statistics recording application used for managing classes of students. It was created with NUS tutors in mind, but can be extended to tutors or teachers from other organizations as well. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

=== Preface
This section serves to inform you of the improvements I made to the project, including code, documentation and administrative tasks.

* *Major enhancement*: Grade Statistics
** What it does: Calculates the statistics for the grades of an individual assignment or the overall class.
** Justification: This feature enables tutors to analyse the grades of students to provide relative feedback based on the performance of the class.
** Highlights: Provides high, low, 25th/75th percentiles, average, and median of the grades.
** Credits:

* *Major enhancement*: Attendance Model
** What it does: Provides a representation of an attendance session for a particular date.
** Justification: This enhancement provides the model for the attendance feature.
** Highlights: This enables a mapping between each student and multiple attendance sessions
               with a record of attendance/absense for that session.
** Credits:

* *Minor enhancement*: Calculate and display the assignment grades when a student is selected.

* *Code contributed*: [https://github.com/CS2103-AY1819S1-W12-4/main/commits/master?author=robertvictoreen] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Review pull requests:
** Enhancements to existing features:
***
** Documentation:
*** UserGuide / DeveloperGuide
** Community:
***
** Tools:
***

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=assignmentstats]

include::../UserGuide.adoc[tag=classstats]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=attendance]


== PROJECT:

---

_{Optionally, you may include other projects in your portfolio.}_
